wazuh/wazuh-virtual-machines

- CHANGELOG.md
- ami/playbooks/build_ami_packages.yaml
- ami/wazuh-ami-customizer.sh
- ami/wazuh-customizer.sh
close https://github.com/wazuh/wazuh-virtual-machines/issues/92
Because AWS had some issues with the customization of the AMI causing them to be unable to access the VM, we made some changes to the customization script, creating specific functions and adding checkpoints to validate the operation of the services after the certificate changes.
<details>
<summary>Boot Time</summary>
```console
cbordon@cbordon-MS-7C88:~/Downloads$ while ! ssh -i cbordon-testing-key.pem -o StrictHostKeyChecking=no wazuh-user@52.87.170.31 exit; do echo "$(date): Retrying..."; sleep 5; done
Warning: Permanently added '52.87.170.31' (ED25519) to the list of known hosts.
wazuh-user@52.87.170.31: Permission denied (publickey,gssapi-keyex,gssapi-with-mic).
mar 22 oct 2024 08:28:01 -03: Retrying... …
```
> Improvements to AMI customization script

- CHANGELOG.md
related https://github.com/wazuh/wazuh-virtual-machines/issues/104
Merge 4.9.2 into 4.10.0
> Merge 4.9.2 into 4.10.0

- .github/workflows/builder_OVA.yaml
- .github/workflows/packages_builder_ami.yaml
> Merge 4.10.1 into 4.11.0

- .github/workflows/builder_OVA.yaml
- .github/workflows/packages_builder_ami.yaml
- CHANGELOG.md
- ami/40-wazuh-banner
- ami/playbooks/build_ami_packages.yaml
- ami/wazuh-ami-customizer.service
- ami/wazuh-ami-customizer.sh
- ami/wazuh-ami-customizer.timer
> Merge 4.11.0 into 4.12.0

- CHANGELOG.md
Related: https://github.com/wazuh/wazuh-virtual-machines/issues/172
> Updated changelog for v4.11.0-alpha1

- .github/workflows/builder_OVA.yaml
- CHANGELOG.md
- ova/provision.sh
- ova/workflow_assets/ova_configurer.py
- https://github.com/wazuh/wazuh-virtual-machines/issues/175
The aim of this PR is to fix the OVA creation process to support the build in the different stages.
Also I fixed the deletion of the AWS instace in the workflow.
> Fix the ova workflow for stages support and AWS instance deletion

- .github/workflows/builder_OVA.yaml
- .github/workflows/packages_builder_ami.yaml
- CHANGELOG.md
- VERSION.json
- ova/generate_ova.sh
close https://github.com/wazuh/wazuh-virtual-machines/issues/210
> Updated VERSION file to the new standard

- .github/workflows/builder_OVA.yaml
- .github/workflows/packages_builder_ami.yaml
- CHANGELOG.md
- VERSION.json
close https://github.com/wazuh/wazuh-virtual-machines/issues/227
> Bump branch 4.13.0 to 4.13.0 version

- CHANGELOG.md
- ami/playbooks/build_ami_packages.yaml
- ova/provision.sh
Closes #222
The objective of this PR is to update the AMI and OVA to take the new indices into account in their creation.
The tests will not be performed by management definition, it was validated that the applied changes take into account all the new indexes created in https://github.com/wazuh/wazuh/tree/dev/fim-syscollector-global-queries/src/wazuh_modules/inventory_harvester/indexer/template
> Updated the regular expression for the new indexes

- CHANGELOG.md
> Merge 4.11.2 into 4.12.0

- .github/workflows/builder_OVA.yaml
- .github/workflows/packages_builder_ami.yaml
- CHANGELOG.md
> Merge 4.12.0 into 4.13.0

- .github/workflows/builder_OVA.yaml
- .github/workflows/packages_builder_ami.yaml
- CHANGELOG.md
- VERSION.json
close https://github.com/wazuh/wazuh-virtual-machines/issues/250
Bump 4.12.1 branch
> Bump 4.12.1 branch

- .github/workflows/builder_OVA.yaml
- .github/workflows/packages_builder_ami.yaml
- CHANGELOG.md
- VERSION.json
> Bump to 4.12.2

- .github/workflows/builder_OVA.yaml
- .github/workflows/packages_builder_ami.yaml
- CHANGELOG.md
- VERSION.json
- tests/test_configurer/test_ova/test_ova_post_configurer/test_ova_post_configurer.py
- wazuh_vm_tester/README.md
- wazuh_vm_tester/src/vm_tester/config.py
close https://github.com/wazuh/wazuh-virtual-machines/issues/293
Bumped 6.0.0 branch to 6.0.0 version
> Bumped 6.0.0 branch

- .github/workflows/builder_OVA.yaml
- .github/workflows/packages_builder_ami.yaml
- CHANGELOG.md
- VERSION.json
close https://github.com/wazuh/wazuh-virtual-machines/issues/295
Bumped main branch to 5.0.0 version
> Bumped main branch to 5.0.0

- .github/workflows/builder_OVA.yaml
- .github/workflows/packages_builder_ami.yaml
- CHANGELOG.md
- VERSION.json
close https://github.com/wazuh/wazuh-virtual-machines/issues/303
Bumped 4.14.0 branch to 4.14.0 version
> Bumped 4.14.0 branch to 4.14.0 version

- CHANGELOG.md
> Remove 4.12.2 references from 4.13.0 branch

- VERSION.json
> Bumped 4.12.1 stage

- VERSION.json
Issue: https://github.com/wazuh/wazuh-virtual-machines/issues/323
> Bump test/323-integrate-bumper-script-via-github-action branch

- .github/workflows/4_bumper_repository.yml
- CHANGELOG.md
- tools/repository_bumper.sh
> Merge 4.14.0 into main

- .github/workflows/builder_OVA.yaml
- .github/workflows/packages_builder_ami.yaml
- CHANGELOG.md
- VERSION.json
Issue: https://github.com/wazuh/wazuh-qa-automation/issues/2625
> Bump test/554-test branch

- .github/workflows/builder_OVA.yaml
- .github/workflows/packages_builder_ami.yaml
- CHANGELOG.md
- VERSION.json
Issue: https://github.com/wazuh/wazuh-qa-automation/issues/3035
> Bump 4.14.1 branch

- .github/workflows/builder_OVA.yaml
- .github/workflows/packages_builder_ami.yaml
- CHANGELOG.md
- VERSION.json
Related: https://github.com/wazuh/wazuh-virtual-machines/issues/380
> Merge 4.13.0 into 4.13.1

- .github/workflows/packages_builder_ami.yaml
related: https://github.com/wazuh/wazuh-automation/issues/2541
Fixed inventory file creation for AMI build.
TEST: https://github.com/wazuh/wazuh-virtual-machines/actions/runs/16889350370/job/47844915448
> Fixed inventory file creation in AMI build

- CHANGELOG.md
Related: https://github.com/wazuh/wazuh-virtual-machines/issues/388
> Merge 4.14.0 into 4.14.1

- CHANGELOG.md
Related: https://github.com/wazuh/wazuh-virtual-machines/issues/388
> Merge 4.14.1 into main

- .github/workflows/packages_builder_ami.yaml
- https://github.com/wazuh/wazuh-virtual-machines/issues/393
> Merge 4.10.3 into 4.10.4

- CHANGELOG.md
- provisioner/utils/enums.py
- tests/test_provisioner/test_models/test_utils/test_helpers.py
- https://github.com/wazuh/internal-devel-requests/issues/2564
> Update bucket references to corresponding new resources

- .github/workflows/builder_OVA.yaml
- .github/workflows/packages_builder_ami.yaml
- CHANGELOG.md
- VERSION.json
Issue: https://github.com/wazuh/wazuh-qa-automation/issues/3910
> Bump 4.13.1 branch
